// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtEfSrOs6e-vUHF9qm4dFsmc0NTuzeJIA',
    appId: '1:10222707395:web:f5a31ef9c6f431300e3876',
    messagingSenderId: '10222707395',
    projectId: 'changarroapp-14917',
    authDomain: 'changarroapp-14917.firebaseapp.com',
    storageBucket: 'changarroapp-14917.firebasestorage.app',
    measurementId: 'G-6BQC0HJ6B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVzORaNN8OyKJXQ_JV9Nl3hVVxHf1UQg',
    appId: '1:10222707395:android:84d8ebff77fc84520e3876',
    messagingSenderId: '10222707395',
    projectId: 'changarroapp-14917',
    storageBucket: 'changarroapp-14917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaG_9GZiRlXYuET6eaAfFsAXgvVTBybPA',
    appId: '1:10222707395:ios:dbc8bc7e1ec481860e3876',
    messagingSenderId: '10222707395',
    projectId: 'changarroapp-14917',
    storageBucket: 'changarroapp-14917.firebasestorage.app',
    iosBundleId: 'com.example.changarroMovile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaG_9GZiRlXYuET6eaAfFsAXgvVTBybPA',
    appId: '1:10222707395:ios:dbc8bc7e1ec481860e3876',
    messagingSenderId: '10222707395',
    projectId: 'changarroapp-14917',
    storageBucket: 'changarroapp-14917.firebasestorage.app',
    iosBundleId: 'com.example.changarroMovile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtEfSrOs6e-vUHF9qm4dFsmc0NTuzeJIA',
    appId: '1:10222707395:web:b13d03c2f0210d610e3876',
    messagingSenderId: '10222707395',
    projectId: 'changarroapp-14917',
    authDomain: 'changarroapp-14917.firebaseapp.com',
    storageBucket: 'changarroapp-14917.firebasestorage.app',
    measurementId: 'G-M0P1M7ER7K',
  );
}
